### ISSUE TITLE
Demos do not work on newest Google Chrome

### ISSUE THREAD

**Issue by beruic** [arbelh/HalfStyle#9]
Newest google chrome only work on single characters

**Comment by beruic** [comment]
![image](https://user-images.githubusercontent.com/724716/28156513-5fe76932-67b3-11e7-8e7c-42742de736ee.png)

**Comment by arbelh** [comment]
Thank you for reporting. The Google Chrome v 59.x issue is resolved.

**Comment by beruic** [comment]
I can confirm that. Well done :)
